### ISSUE TITLE
Problem with running action

### ISSUE THREAD

**Issue by gep13** [max/awesome-lint#1]
I am trying to fix all the awesome-lint errors that are appearing on this repository:

https://github.com/sdras/awesome-actions

I have been able to remove all of them, with the exception of this one, which appears when your GitHub Action is executed:

![image](https://user-images.githubusercontent.com/1271146/53527845-ec6a0580-3adf-11e9-94c5-722541952915.png)

However, when I run awesome-lint locally, I get the following:

![image](https://user-images.githubusercontent.com/1271146/53527883-01469900-3ae0-11e9-87c5-16b3fc468231.png)

Looking at this rule:

https://github.com/sindresorhus/awesome-lint/blob/master/rules/git-repo-age.js

It looks like 'git' is a requirement.  Is it possible that git isn't currently available on the docker image that you are using?  Or, can you suggest another reason why this rule would be triggered for this repository?

Thanks

//cc @sdras

**Comment by gep13** [comment]
@max just wanted to check in to see if you had any ideas about this.  Thanks

**Comment by max** [comment]
@gep13 Thank you for digging into this. I was able to verify that it’s indeed because of the missing `git` dependency. I tried out #2 against [sdras/awesome-actions](https://github.com/sdras/awesome-actions) and everything now passes.

Pro tip: If you want to debug GitHub Actions locally check out [nektos/act](https://github.com/nektos/act).

I hope you have a great weekend!

**Comment by gep13** [comment]
@max thanks for getting this fixed!

**Comment by max** [comment]
No problem. I also cut a release fo if you would like to pin the Action to
`@1.0.0` instead of `@master` that should work as well.

**Comment by gep13** [comment]
I can confirm that this is now working:

![image](https://user-images.githubusercontent.com/1271146/53686604-1eb67580-3d21-11e9-86ef-588c4e269ced.png)

Thanks again for your help in getting this fixed!
